### ISSUE TITLE
Need a setting to not filter descriptions only titles

### ISSUE THREAD

**Issue by GarretSidzaka** [rikharink/keywordblocker#331]
hello,

we are blocking a social media provider's videos (specificially tik tok).   we got the block working just fine!  except there are many many videos getting blocked that are not from tik tok or have tik tok in the title, but rather the description of the author contains a block that has all the user's social media links, including tik tok.  I would still want to see these videos as they are not from tik tok, as they dont have that in the title.

can we make a feature where can can toggle what we are blocking?   i see in the SRC that you have a "const description" variable that gets compared with the keyword block pattern.   this could probably be made configurable im just terrible with this language.

We could have it not check description for the keyword with via configuration?

thank you for the hard work and sharing it with the community.

**Comment by rikharink** [comment]
I have a setting for that already I think. Can you try unchecking the setting circled in red?
![image](https://user-images.githubusercontent.com/272554/98115934-dcefb200-1ea7-11eb-9c50-071661ff3c32.png)

If this doesn't solve your issue than let me know and I'll look into it!

Kind regards,

Rik

**Comment by GarretSidzaka** [comment]
hello i can confirm i had that checked.   thank you.  im going to close this ticket and i will reopen if she is still getting issues :)
