### ISSUE TITLE
Blocked videos / channels on front page

### ISSUE THREAD

**Issue by beerbotboffin** [rikharink/keywordblocker#44]
Videos with blocked keywords / channels appear on the main recommended page unblocked. 

1. Add a keyword to block say 'impeachment'
2. Go to Home and in the recommended section there's still videos with that keyword in the title.
3. Clicking on the video will open it and then it's blocked, but not on the thumbnail.

If a video / channel name contains a keyword, it should be blocked.

![Block1](https://user-images.githubusercontent.com/4359388/70491356-d39d7e80-1b4c-11ea-910c-316f41a1f2b5.JPG)
![Block2](https://user-images.githubusercontent.com/4359388/70491358-d4ceab80-1b4c-11ea-9ead-198df2a0b16b.JPG)

 - OS: Win7
 - Browser Chrome
 - Version

**Comment by Meidor** [comment]
I found that YouTube had changed the frontpage layout and that's why it didn't block anymore.
I've fixed that and will release a new version (2.2.0) of the extension shortly.

Thanks for reporting!
