### ISSUE TITLE
Firefox version 2.2.0 on addons.mozilla.org is broken

### ISSUE THREAD

**Issue by link2xt** [rikharink/keywordblocker#51]
CSS styles are not loaded when I install https://addons.mozilla.org/en-US/firefox/addon/keyword-blocker/ in Firefox. This seems to be due to the bug described in README: "Due to a bug in html-webpack-plugin injected paths to the stylesheets will have a backslash instead to a forward slash. This will lead to problems when running the plugin on firefox."

Current version uploaded to addons.mozilla.org is not usable.

**Comment by rikharink** [comment]
Thanks for submitting this issue. I'll make a new build and fix this tonight (together with your link fix pr thank you!).

**Comment by rikharink** [comment]
I've submitted v2.2.1 for review and I hope this fixes the problems on firefox!

**Comment by link2xt** [comment]
Just updated. It is fixed, thanks!
